/**
 * Central feature registry — single source of truth for all app features.
 * When a new feature is added, register it here and it will automatically
 * appear in the How To catalog, search, and any feature-listing UI.
 */

export interface FeatureEntry {
  id: string;
  name: string;
  category: "invoices" | "inventory" | "marketing" | "tools" | "accounting" | "suppliers" | "shopify" | "settings";
  description: string;
  howTo: string[];           // step-by-step instructions
  tips?: string[];           // optional power-user tips
  icon: string;              // emoji icon
  flowKey?: string;          // maps to activeFlow in Index.tsx
  tabKey?: string;           // maps to activeTab
  keywords: string[];        // for search
}

export const featureRegistry: FeatureEntry[] = [
  // ── Invoices & Intake ──
  {
    id: "invoice_import",
    name: "Import Invoice",
    category: "invoices",
    icon: "📄",
    description: "Upload PDF, Excel, CSV, Word, or photo invoices and let AI extract product data automatically.",
    howTo: [
      "Go to Home and tap 'Import Invoice'",
      "Upload a PDF, Excel, CSV, Word file, or take a photo",
      "Optionally enter the supplier name and any custom AI instructions",
      "Wait for AI to extract and enrich all product data",
      "Review the enriched products — edit any fields that need correction",
      "Choose your export format (Shopify CSV, Matrixify, etc.) and download",
    ],
    tips: ["Add custom AI instructions like 'Map first price column to cost' for tricky invoices", "The system learns supplier formats over time for faster processing"],
    flowKey: "invoice",
    keywords: ["upload", "pdf", "excel", "csv", "scan", "import", "invoice"],
  },
  {
    id: "scan_mode",
    name: "Scan Mode",
    category: "invoices",
    icon: "📷",
    description: "Use your camera to scan barcodes or take photos of physical invoices for instant processing.",
    howTo: [
      "Go to Home and tap 'Scan Mode'",
      "Point your camera at a barcode or invoice",
      "The app will auto-detect and extract the data",
      "Review and confirm the extracted information",
    ],
    flowKey: "scan_mode",
    keywords: ["scan", "barcode", "camera", "photo"],
  },
  {
    id: "email_inbox",
    name: "Email Inbox",
    category: "invoices",
    icon: "📧",
    description: "Forward supplier invoices to your dedicated email address for automatic processing.",
    howTo: [
      "Go to Home and tap 'Email Inbox'",
      "Copy your unique forwarding email address",
      "Forward any supplier invoice to that address",
      "The invoice will appear in your inbox for processing",
      "Click on any email to start the invoice import flow",
    ],
    flowKey: "email_inbox",
    keywords: ["email", "forward", "inbox", "supplier"],
  },
  {
    id: "packing_slip",
    name: "Packing Slips",
    category: "invoices",
    icon: "📦",
    description: "Generate professional packing slips from your orders for shipping.",
    howTo: [
      "Go to Invoices tab and tap 'Packing Slips'",
      "Select the orders you want to create slips for",
      "Customise the packing slip layout if needed",
      "Print or download the generated slips",
    ],
    flowKey: "packing_slip",
    keywords: ["packing", "shipping", "slip", "print"],
  },
  {
    id: "order_form",
    name: "Order Form",
    category: "invoices",
    icon: "📋",
    description: "Create purchase order forms to send to your suppliers.",
    howTo: [
      "Go to Home and tap 'Order Form'",
      "Select or create a supplier",
      "Add products with quantities and costs",
      "Preview and download the order form as PDF or CSV",
      "Send directly to your supplier via email",
    ],
    flowKey: "order_form",
    keywords: ["order", "purchase", "form", "supplier"],
  },

  // ── Inventory ──
  {
    id: "purchase_orders",
    name: "Purchase Orders",
    category: "inventory",
    icon: "🛒",
    description: "Create, track, and receive purchase orders with automatic stock level updates.",
    howTo: [
      "Go to Home and tap 'Purchase Orders'",
      "Click 'Create PO' to start a new purchase order",
      "Select a supplier and add line items",
      "Set expected delivery date and notes",
      "When stock arrives, use 'Receive' to update quantities",
      "The PO status updates automatically: Draft → Sent → Partially Received → Received",
    ],
    flowKey: "purchase_orders",
    keywords: ["purchase", "order", "po", "receive", "stock"],
  },
  {
    id: "restock_analytics",
    name: "Restock Check",
    category: "inventory",
    icon: "📊",
    description: "AI-powered restock recommendations based on sales velocity and lead times.",
    howTo: [
      "Go to Home and tap 'Restock Check'",
      "View products sorted by restock urgency",
      "Review recommended order quantities based on sales data",
      "Create purchase orders directly from recommendations",
    ],
    flowKey: "restock",
    keywords: ["restock", "reorder", "analytics", "demand"],
  },
  {
    id: "stock_monitor",
    name: "Stock Monitor",
    category: "inventory",
    icon: "📡",
    description: "Real-time stock level monitoring with configurable alerts for low stock.",
    howTo: [
      "Go to Home and tap 'Stock Monitor'",
      "Set minimum stock thresholds per product or category",
      "Enable notifications for low-stock alerts",
      "View the live dashboard of all monitored products",
    ],
    flowKey: "stock_monitor",
    keywords: ["stock", "monitor", "alert", "low stock", "threshold"],
  },
  {
    id: "stocktake",
    name: "Stocktake",
    category: "inventory",
    icon: "📋",
    description: "Conduct full or partial stocktakes with barcode scanning and variance reporting.",
    howTo: [
      "Go to the Stocky hub or Home shortcuts",
      "Tap 'New Stocktake' and select a location",
      "Scan barcodes or manually enter counts for each product",
      "Review variances between expected and counted quantities",
      "Submit the stocktake to update inventory records",
    ],
    flowKey: "stocktake_module",
    keywords: ["stocktake", "count", "variance", "audit"],
  },
  {
    id: "transfer_orders",
    name: "Transfer Orders",
    category: "inventory",
    icon: "🔄",
    description: "Move stock between locations with tracked transfer orders.",
    howTo: [
      "Navigate to Transfer Orders from the Stocky hub",
      "Select source and destination locations",
      "Add products and quantities to transfer",
      "Ship the transfer and receive at the destination",
    ],
    flowKey: "transfer_orders",
    keywords: ["transfer", "location", "move", "warehouse"],
  },
  {
    id: "inventory_planning",
    name: "Inventory Planning",
    category: "inventory",
    icon: "🗓️",
    description: "Plan future inventory needs with demand forecasting and seasonal analysis.",
    howTo: [
      "Go to Home and tap 'Inventory Planning'",
      "Review demand forecasts based on historical sales",
      "Adjust for upcoming seasons or promotions",
      "Generate optimised order plans for each supplier",
    ],
    flowKey: "inventory_planning",
    keywords: ["planning", "forecast", "demand", "seasonal"],
  },
  {
    id: "margin_protection",
    name: "Margin Protection",
    category: "inventory",
    icon: "🛡️",
    description: "Set minimum margin thresholds and get alerts when products fall below.",
    howTo: [
      "Navigate to Margin Protection from Tools or Home",
      "Set your minimum margin percentage per category or brand",
      "Review flagged products that are below your thresholds",
      "Take action: adjust prices, pause sales, or accept the margin",
    ],
    flowKey: "margin_protection",
    keywords: ["margin", "protection", "profit", "threshold"],
  },
  {
    id: "markdown_ladder",
    name: "Markdown Ladder",
    category: "inventory",
    icon: "📉",
    description: "Automate progressive markdown pricing for slow-moving stock.",
    howTo: [
      "Navigate to Markdown Ladder from Tools or Home",
      "Create a new ladder with your markdown stages (e.g. 20%, 30%, 50% off)",
      "Select products or categories to apply the ladder to",
      "Set the trigger: days without sale, or manual",
      "The system will automatically progress through stages",
    ],
    flowKey: "markdown_ladder",
    keywords: ["markdown", "clearance", "sale", "discount", "ladder"],
  },

  // ── Marketing ──
  {
    id: "google_ads_setup",
    name: "Google Ads Setup",
    category: "marketing",
    icon: "🎯",
    description: "Set up Google Shopping campaigns with margin-aware bidding.",
    howTo: [
      "Go to Tools → Marketing section → Google Ads Setup",
      "Connect your Google Merchant Center account",
      "Configure campaign budget and target ROAS",
      "Set margin-based bid adjustments",
      "Launch your campaign with AI-optimised product titles",
    ],
    flowKey: "google_ads_setup",
    keywords: ["google", "ads", "shopping", "campaign", "ppc"],
  },
  {
    id: "meta_ads_setup",
    name: "Meta Ads Setup",
    category: "marketing",
    icon: "📘",
    description: "Set up Meta/Facebook ad campaigns for your products.",
    howTo: [
      "Go to Tools → Marketing section → Meta Ads Setup",
      "Connect your Meta Business account",
      "Choose your campaign objective (sales, traffic, awareness)",
      "Select products and configure targeting",
      "Set budget and schedule, then launch",
    ],
    flowKey: "meta_ads_setup",
    keywords: ["meta", "facebook", "instagram", "ads", "social"],
  },
  {
    id: "seo_writer",
    name: "SEO Writer",
    category: "marketing",
    icon: "✍️",
    description: "Generate SEO-optimised product titles and meta descriptions using AI.",
    howTo: [
      "Go to Tools and find 'SEO Writer'",
      "Enter or paste your product details",
      "AI will generate an optimised title (<60 chars) and description (<160 chars)",
      "Copy the results to your Shopify listing or export",
    ],
    keywords: ["seo", "title", "meta", "description", "search"],
  },
  {
    id: "organic_seo",
    name: "Organic SEO Blog",
    category: "marketing",
    icon: "📝",
    description: "Build topical authority with AI-generated blog posts targeting your product keywords.",
    howTo: [
      "Go to Tools → Marketing → Organic SEO Blog",
      "Enter your target topic or keyword cluster",
      "AI generates a full blog post with internal linking",
      "Review, edit, and publish to your Shopify blog",
    ],
    flowKey: "organic_seo",
    keywords: ["blog", "seo", "organic", "content", "authority"],
  },
  {
    id: "collection_seo",
    name: "Collection SEO AI",
    category: "marketing",
    icon: "🏷️",
    description: "SEO-optimise your Shopify collections for better Google rankings.",
    howTo: [
      "Go to Tools → Collection SEO AI",
      "Select collections from your Shopify store",
      "AI generates optimised titles, descriptions, and meta tags",
      "Review and push changes to Shopify",
    ],
    flowKey: "collection_seo",
    keywords: ["collection", "seo", "category", "ranking"],
  },
  {
    id: "social_media",
    name: "Social Media",
    category: "marketing",
    icon: "📱",
    description: "Auto-generate social media captions and product announcements.",
    howTo: [
      "Go to Tools → Marketing → Social Media",
      "Select products to promote",
      "Choose platform (Instagram, Facebook, TikTok)",
      "AI generates captions with hashtags and emojis",
      "Copy or schedule posts directly",
    ],
    flowKey: "social_media",
    keywords: ["social", "instagram", "facebook", "caption", "post"],
  },
  {
    id: "competitor_intel",
    name: "Competitor Intel",
    category: "marketing",
    icon: "🕵️",
    description: "Analyse competitor pricing, positioning, and product ranges.",
    howTo: [
      "Go to Tools → Marketing → Competitor Intel",
      "Add competitor Shopify store URLs",
      "The system will fetch and compare product data",
      "Review pricing differences and market positioning",
    ],
    flowKey: "competitor_intel",
    keywords: ["competitor", "price", "compare", "intelligence"],
  },
  {
    id: "price_monitor",
    name: "Competitor Price Monitor",
    category: "marketing",
    icon: "💰",
    description: "Monitor competitor prices in real-time and one-click price match or beat.",
    howTo: [
      "Go to Tools → Marketing → Price Monitor",
      "Add competitors with their Shopify store URLs",
      "Select your products to monitor",
      "Click 'Fetch Prices' to scan competitor stores",
      "View the comparison dashboard with price differences",
      "Use 'Match' or 'Beat by %' to update your prices",
      "Export changes as CSV for bulk Shopify import",
    ],
    tips: ["Only works with Shopify competitor stores via their /products.json endpoint", "Prices are cached for 2-4 hours to avoid excessive requests"],
    flowKey: "competitor_intel",
    keywords: ["price", "monitor", "match", "competitor", "beat"],
  },
  {
    id: "geo_agentic",
    name: "Local SEO",
    category: "marketing",
    icon: "📍",
    description: "Geo-targeted SEO strategies for local store visibility.",
    howTo: [
      "Go to Tools → Marketing → Local SEO",
      "Enter your store's physical locations",
      "AI generates location-specific landing pages and schema markup",
      "Implement the recommendations for better local search rankings",
    ],
    flowKey: "geo_agentic",
    keywords: ["local", "geo", "location", "map", "seo"],
  },
  {
    id: "performance_dashboard",
    name: "Ad Performance",
    category: "marketing",
    icon: "📈",
    description: "Track ROI, spend, and ROAS across all your advertising channels.",
    howTo: [
      "Go to Tools → Marketing → Ad Performance",
      "Connect your ad accounts (Google, Meta)",
      "View unified dashboard with spend, revenue, and ROAS",
      "Drill down into individual campaigns for detailed metrics",
    ],
    flowKey: "performance",
    keywords: ["performance", "roas", "roi", "spend", "ads"],
  },
  {
    id: "feed_optimise",
    name: "AI Feed Optimisation",
    category: "marketing",
    icon: "🤖",
    description: "Generate Google Shopping product_detail attributes using AI.",
    howTo: [
      "Go to Tools → AI Feed Optimisation",
      "Upload your product CSV or connect Shopify",
      "AI analyses each product and generates optimised feed attributes",
      "Review and download the enhanced feed",
    ],
    flowKey: "feed_optimise",
    keywords: ["feed", "google", "shopping", "optimise", "product"],
  },
  {
    id: "feed_health",
    name: "Google Feed Health",
    category: "marketing",
    icon: "🏥",
    description: "Fix missing gender, age_group, color fields and push to Shopify.",
    howTo: [
      "Go to Tools → Google Feed Health",
      "The tool scans your products for missing required fields",
      "Review AI suggestions for gender, age group, and color",
      "Apply fixes individually or in bulk",
      "Push corrected data to Shopify",
    ],
    flowKey: "feed_health",
    keywords: ["feed", "health", "gender", "color", "age"],
  },
  {
    id: "collab_seo",
    name: "Collab SEO",
    category: "marketing",
    icon: "🤝",
    description: "Manage SEO collaboration campaigns with brand partners.",
    howTo: [
      "Go to Tools → Collab SEO",
      "Create a new campaign and add partner brands",
      "Set up cross-linking and co-marketing content",
      "Track campaign performance and backlink growth",
    ],
    flowKey: "collab_seo",
    keywords: ["collab", "partnership", "backlink", "seo"],
  },

  // ── Tools ──
  {
    id: "price_lookup",
    name: "Price Lookup",
    category: "tools",
    icon: "🔍",
    description: "Look up retail prices from brand websites and trusted aggregators.",
    howTo: [
      "Go to Tools → Price Lookup",
      "Enter the product name and brand",
      "The system searches official brand sites and retail aggregators",
      "View matched prices with source URLs and confidence scores",
      "Results are cached for faster future lookups",
    ],
    tips: ["Amazon and eBay are never used as RRP sources", "Uses local currency prices matching your store config"],
    flowKey: "price_lookup",
    keywords: ["price", "lookup", "rrp", "retail", "search"],
  },
  {
    id: "tag_builder",
    name: "Tag Builder",
    category: "tools",
    icon: "🏷️",
    description: "Build and customise Shopify product tags with a multi-layer formula.",
    howTo: [
      "Go to Tools → Tag Builder",
      "View the current tag formula layers (gender, type, brand, etc.)",
      "Add or remove layers to customise your tag structure",
      "Set special rules for property detection (e.g. 'underwire', 'chlorine resistant')",
      "Preview generated tags for sample products",
    ],
    keywords: ["tag", "label", "shopify", "category", "filter"],
  },
  {
    id: "brand_directory",
    name: "Brand Reference",
    category: "tools",
    icon: "🌐",
    description: "Searchable directory of brand websites for quick reference.",
    howTo: [
      "Go to Tools → Brand Reference",
      "Browse or search the pre-loaded brand directory",
      "Add new brands with their website URLs",
      "Export or import brand lists as CSV",
    ],
    keywords: ["brand", "directory", "website", "reference"],
  },
  {
    id: "ai_instructions",
    name: "AI Instructions",
    category: "tools",
    icon: "🧠",
    description: "Set custom rules for how AI processes your invoices.",
    howTo: [
      "Go to Tools → AI Instructions",
      "Add rules using natural language (e.g. 'Add brand name at the start of every product name')",
      "Use quick-insert templates for common rules",
      "Rules apply to all future invoice processing",
    ],
    keywords: ["ai", "rules", "instructions", "custom", "prompt"],
  },
  {
    id: "google_feed",
    name: "Google Feed Preview",
    category: "tools",
    icon: "🛍️",
    description: "Preview and download your Google Shopping feed in XML or TSV format.",
    howTo: [
      "Go to Tools → Google Feed Preview",
      "Upload your Shopify product CSV",
      "Preview the generated Google Shopping feed",
      "Download as XML or TSV for Merchant Center upload",
    ],
    keywords: ["google", "feed", "shopping", "xml", "tsv"],
  },
  {
    id: "lightspeed_convert",
    name: "Lightspeed Converter",
    category: "tools",
    icon: "⚡",
    description: "Convert Lightspeed product exports to Shopify-ready CSV format.",
    howTo: [
      "Go to Tools → Lightspeed Converter",
      "Upload your Lightspeed product export CSV",
      "Map columns to Shopify fields",
      "Download the converted Shopify-ready CSV",
    ],
    flowKey: "lightspeed_convert",
    keywords: ["lightspeed", "convert", "migrate", "csv"],
  },
  {
    id: "image_optimise",
    name: "Image Optimisation AI",
    category: "tools",
    icon: "🖼️",
    description: "Generate alt text, optimised filenames, and quality analysis for product images.",
    howTo: [
      "Go to Tools → Image Optimisation AI",
      "Upload product images or connect to Shopify",
      "AI generates SEO-friendly alt text and filenames",
      "Review quality scores and compression recommendations",
      "Apply changes to update your Shopify store",
    ],
    flowKey: "image_optimise",
    keywords: ["image", "alt text", "optimise", "compress", "seo"],
  },
  {
    id: "csv_seo",
    name: "CSV SEO Optimizer",
    category: "tools",
    icon: "📊",
    description: "Upload a Shopify CSV, AI-optimize SEO fields, and download the ready-to-import file.",
    howTo: [
      "Go to Tools → CSV SEO Optimizer",
      "Upload your Shopify product CSV export",
      "AI optimises titles, descriptions, and meta fields",
      "Review changes side-by-side",
      "Download the optimised CSV and re-import to Shopify",
    ],
    flowKey: "csv_seo",
    keywords: ["csv", "seo", "bulk", "optimize", "shopify"],
  },
  {
    id: "bulk_sale",
    name: "Bulk Sale Pricing",
    category: "tools",
    icon: "💸",
    description: "Apply sale pricing to products in bulk with filters and rounding rules.",
    howTo: [
      "Go to Home and tap 'Bulk Sale'",
      "Upload your Shopify product CSV export",
      "Filter products by vendor, tag, or product type",
      "Set discount percentage and rounding rule",
      "Preview all changes before downloading",
      "Download the updated CSV and re-import to Shopify",
    ],
    flowKey: "sale",
    keywords: ["sale", "discount", "bulk", "pricing", "markdown"],
  },
  {
    id: "price_adjust",
    name: "Price Adjustment",
    category: "tools",
    icon: "💲",
    description: "Adjust prices across your catalog with rules-based pricing strategies.",
    howTo: [
      "Go to Home and tap 'Price Adjust'",
      "Select products to adjust (by brand, type, or individual)",
      "Choose adjustment type: percentage, fixed amount, or margin-based",
      "Preview the new prices before applying",
      "Export or push changes to Shopify",
    ],
    flowKey: "price_adjust",
    keywords: ["price", "adjust", "markup", "margin", "cost"],
  },
  {
    id: "style_grouping",
    name: "Style Grouping",
    category: "tools",
    icon: "👔",
    description: "Group product variants by style for cleaner Shopify listings.",
    howTo: [
      "Go to Tools → Style Grouping",
      "Upload your product data",
      "AI identifies products that should be grouped as variants",
      "Review and adjust groupings",
      "Export the restructured data",
    ],
    flowKey: "style_grouping",
    keywords: ["style", "group", "variant", "merge", "product"],
  },
  {
    id: "learning_memory",
    name: "Learning Memory",
    category: "tools",
    icon: "🧠",
    description: "View patterns the AI has learned from your supplier invoices.",
    howTo: [
      "Go to Tools → Learning Memory",
      "Browse learned patterns grouped by supplier",
      "See how the AI maps columns and extracts data",
      "Delete or adjust learned patterns if needed",
    ],
    keywords: ["learn", "memory", "pattern", "supplier", "template"],
  },

  // ── Suppliers ──
  {
    id: "supplier_management",
    name: "Supplier Management",
    category: "suppliers",
    icon: "🏭",
    description: "Manage your supplier contacts, spending, and performance data.",
    howTo: [
      "Go to Home and tap 'Suppliers'",
      "View all suppliers with total spend and margin data",
      "Add new suppliers with contact details and currency",
      "Click a supplier to see their invoice history and catalog",
    ],
    flowKey: "suppliers",
    keywords: ["supplier", "vendor", "contact", "manage"],
  },
  {
    id: "supplier_emails",
    name: "Supplier Email Templates",
    category: "suppliers",
    icon: "✉️",
    description: "Pre-built email templates for common supplier communications.",
    howTo: [
      "Go to Tools → Supplier Emails",
      "Choose a template (price list request, reorder, complaint, etc.)",
      "Customise the template with your details",
      "Copy to clipboard or send directly",
    ],
    keywords: ["email", "template", "supplier", "communication"],
  },
  {
    id: "supplier_catalog",
    name: "Catalog Memory",
    category: "suppliers",
    icon: "📚",
    description: "Track all products across your supplier catalogs with cost and lead time data.",
    howTo: [
      "Go to Home and tap 'Catalog Memory'",
      "Browse products grouped by supplier",
      "Search by SKU, barcode, or product name",
      "View cost history and lead time estimates",
    ],
    flowKey: "catalog_memory",
    keywords: ["catalog", "memory", "product", "cost", "lead time"],
  },
  {
    id: "seasons",
    name: "Seasons",
    category: "suppliers",
    icon: "📅",
    description: "Track brand drops and seasonal collections by supplier.",
    howTo: [
      "Go to Tools → Seasons",
      "Add seasons with start/end dates per brand",
      "Track which products belong to each season",
      "View upcoming drops and plan purchasing",
    ],
    flowKey: "seasons",
    keywords: ["season", "drop", "collection", "schedule"],
  },

  // ── Shopify ──
  {
    id: "shopify_push",
    name: "Push to Shopify",
    category: "shopify",
    icon: "🚀",
    description: "Push enriched products directly to your Shopify store via API.",
    howTo: [
      "First connect your store in Account → Store Setup",
      "Enter your Shopify store URL and Admin API access token",
      "After processing an invoice, tap 'Push to Shopify'",
      "Review products before confirming the push",
      "Products will be created or updated in your store",
    ],
    tips: ["Nothing pushes to Shopify without your explicit confirmation", "You can choose to create as Draft or Active products"],
    keywords: ["shopify", "push", "publish", "api", "product"],
  },
  {
    id: "export_collections",
    name: "Export Collections",
    category: "shopify",
    icon: "📤",
    description: "Export all Shopify collections to CSV for backup or editing.",
    howTo: [
      "Go to Tools → Export Collections",
      "Connect your Shopify store if not already done",
      "Click 'Export' to download all collections as CSV",
      "Edit the CSV in Excel or Google Sheets",
    ],
    keywords: ["export", "collection", "csv", "backup"],
  },
  {
    id: "import_collections",
    name: "Import Collections",
    category: "shopify",
    icon: "📥",
    description: "Create or update Shopify collections from a CSV file.",
    howTo: [
      "Go to Tools → Import Collections",
      "Upload your collections CSV file",
      "Map columns to collection fields",
      "Review and confirm the import",
    ],
    keywords: ["import", "collection", "csv", "create", "update"],
  },
  {
    id: "order_sync",
    name: "Shopify Order Sync",
    category: "shopify",
    icon: "🔄",
    description: "Sync orders from Shopify for sales tracking and inventory updates.",
    howTo: [
      "Navigate to Shopify Order Sync from the Stocky hub",
      "Connect your Shopify store",
      "Configure sync frequency and filters",
      "Orders will be imported for sales analytics",
    ],
    flowKey: "order_sync",
    keywords: ["order", "sync", "shopify", "sales", "import"],
  },

  // ── Accounting ──
  {
    id: "accounting_integration",
    name: "Accounting Integration",
    category: "accounting",
    icon: "📒",
    description: "Connect to Xero or MYOB to push invoices and expenses automatically.",
    howTo: [
      "Go to Invoices tab → Accounting",
      "Choose your platform (Xero or MYOB)",
      "Follow the OAuth flow to connect your account",
      "Map invoice categories to your chart of accounts",
      "Push processed invoices to your accounting software",
    ],
    flowKey: "accounting",
    keywords: ["accounting", "xero", "myob", "integration", "bookkeeping"],
  },
  {
    id: "profit_loss",
    name: "Profit & Loss",
    category: "accounting",
    icon: "💹",
    description: "View profit and loss reports based on your invoice and sales data.",
    howTo: [
      "Navigate to Profit & Loss from Home or Invoices",
      "Select date range for the report",
      "View revenue, COGS, and gross margin breakdown",
      "Filter by supplier, category, or product type",
      "Export the report as CSV or PDF",
    ],
    flowKey: "profit_loss",
    keywords: ["profit", "loss", "report", "margin", "revenue"],
  },

  // ── Settings ──
  {
    id: "store_settings",
    name: "Store Settings",
    category: "settings",
    icon: "⚙️",
    description: "Configure your store name, currency, language, industry, and tax region.",
    howTo: [
      "Go to the Account tab",
      "Update your store name, currency, and language",
      "Select your industry for tailored tag and SEO formulas",
      "Set your tax region for accurate GST/VAT calculations",
      "Click 'Save' to apply changes",
    ],
    tabKey: "account",
    keywords: ["settings", "store", "currency", "language", "config"],
  },
  {
    id: "team_management",
    name: "Team Management",
    category: "settings",
    icon: "👥",
    description: "Invite team members and manage roles (Admin, Editor, Viewer).",
    howTo: [
      "Go to Account → Team Management",
      "Click 'Invite Member' and enter their email",
      "Set their role: Admin, Editor, or Viewer",
      "They'll receive an email invitation to join",
      "Manage existing members' roles or remove access",
    ],
    tabKey: "account",
    keywords: ["team", "invite", "role", "user", "permission"],
  },
  {
    id: "billing",
    name: "Billing & Plans",
    category: "settings",
    icon: "💳",
    description: "View your plan, usage metrics, and manage your subscription.",
    howTo: [
      "Go to the Billing tab",
      "View current plan and usage metrics (invoices processed, products tracked)",
      "See monthly invoice count vs plan limit",
      "Upgrade or change plans as needed",
    ],
    tabKey: "billing",
    keywords: ["billing", "plan", "subscription", "usage", "payment"],
  },

  // ── Wholesale ──
  {
    id: "joor",
    name: "JOOR Import",
    category: "invoices",
    icon: "👗",
    description: "Import wholesale orders from JOOR with automatic product enrichment.",
    howTo: [
      "Go to Invoices tab → JOOR Import",
      "Connect your JOOR account or upload export files",
      "Map JOOR fields to your Shopify product structure",
      "Review enriched products and export",
    ],
    flowKey: "joor",
    keywords: ["joor", "wholesale", "fashion", "import"],
  },
  {
    id: "wholesale_import",
    name: "Wholesale Import",
    category: "invoices",
    icon: "🏪",
    description: "Import wholesale line sheets and order forms from various formats.",
    howTo: [
      "Go to Invoices tab → Wholesale Import",
      "Upload a wholesale line sheet (PDF, Excel, or CSV)",
      "The system auto-detects the format and extracts product data",
      "Review and export to Shopify format",
    ],
    flowKey: "wholesale_import",
    keywords: ["wholesale", "linesheet", "import", "bulk"],
  },
  {
    id: "lookbook_import",
    name: "Lookbook Import",
    category: "invoices",
    icon: "📸",
    description: "Extract product data from brand lookbook PDFs using AI vision.",
    howTo: [
      "Go to Invoices tab → Lookbook Import",
      "Upload a brand lookbook PDF",
      "AI extracts product images, names, and details from each page",
      "Review and map to your Shopify product fields",
      "Export the extracted catalog",
    ],
    flowKey: "lookbook_import",
    keywords: ["lookbook", "pdf", "extract", "vision", "catalog"],
  },
];

/** Get all features grouped by category */
export function getFeaturesByCategory(): Record<string, FeatureEntry[]> {
  const grouped: Record<string, FeatureEntry[]> = {};
  for (const f of featureRegistry) {
    if (!grouped[f.category]) grouped[f.category] = [];
    grouped[f.category].push(f);
  }
  return grouped;
}

/** Search features by keyword */
export function searchFeatures(query: string): FeatureEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return featureRegistry;
  return featureRegistry.filter(f =>
    f.name.toLowerCase().includes(q) ||
    f.description.toLowerCase().includes(q) ||
    f.keywords.some(k => k.includes(q))
  );
}

/** Category labels for display */
export const categoryLabels: Record<string, string> = {
  invoices: "Invoices & Intake",
  inventory: "Inventory Management",
  marketing: "Marketing & SEO",
  tools: "Tools & Utilities",
  accounting: "Accounting & Reports",
  suppliers: "Suppliers & Catalogs",
  shopify: "Shopify Integration",
  settings: "Settings & Account",
};

/** Category icons */
export const categoryIcons: Record<string, string> = {
  invoices: "📄",
  inventory: "📦",
  marketing: "📢",
  tools: "🔧",
  accounting: "📒",
  suppliers: "🏭",
  shopify: "🛍️",
  settings: "⚙️",
};
