import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";

interface MeshRow {
  id: string;
  source_suggestion_id: string;
  target_suggestion_id: string;
  link_type: string;
  anchor_text: string;
  source_title?: string;
  target_title?: string;
}

export default function SeoLinkMesh() {
  const { toast } = useToast();
  const [rows, setRows] = useState<MeshRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(false);

  useEffect(() => { void load(); }, []);

  async function load() {
    setLoading(true);
    const { data: links } = await supabase
      .from("collection_link_mesh")
      .select("id,source_suggestion_id,target_suggestion_id,link_type,anchor_text")
      .limit(500);
    const ids = Array.from(new Set((links ?? []).flatMap(l => [l.source_suggestion_id, l.target_suggestion_id])));
    const { data: sugs } = ids.length
      ? await supabase.from("collection_suggestions").select("id,suggested_title").in("id", ids)
      : { data: [] as any[] };
    const titleMap = new Map((sugs ?? []).map((s: any) => [s.id, s.suggested_title]));
    setRows((links ?? []).map((l: any) => ({
      ...l,
      source_title: titleMap.get(l.source_suggestion_id),
      target_title: titleMap.get(l.target_suggestion_id),
    })));
    setLoading(false);
  }

  async function rebuild() {
    setRunning(true);
    try {
      const { data, error } = await supabase.functions.invoke("seo-link-mesh-builder", { body: {} });
      if (error) throw error;
      toast({ title: "Mesh rebuilt", description: `${data?.inserted ?? 0} links` });
      await load();
    } catch (e: any) {
      toast({ title: "Rebuild failed", description: String(e?.message || e), variant: "destructive" });
    } finally {
      setRunning(false);
    }
  }

  return (
    <div className="min-h-screen bg-background text-foreground p-6">
      <div className="max-w-6xl mx-auto space-y-6">
        <header className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">SEO Link Mesh</h1>
            <p className="text-sm text-muted-foreground">
              Internal collection links generated by the 5-rule mesh builder.
            </p>
          </div>
          <Button onClick={rebuild} disabled={running}>
            {running ? "Rebuilding…" : "Rebuild mesh"}
          </Button>
        </header>

        <Card className="p-0 overflow-hidden">
          {loading ? (
            <div className="p-6 text-muted-foreground">Loading…</div>
          ) : rows.length === 0 ? (
            <div className="p-6 text-muted-foreground">No links yet — run rebuild.</div>
          ) : (
            <table className="w-full text-sm">
              <thead className="bg-muted/40 text-left">
                <tr>
                  <th className="p-2">Source</th>
                  <th className="p-2">Type</th>
                  <th className="p-2">Anchor</th>
                  <th className="p-2">Target</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((r) => (
                  <tr key={r.id} className="border-t border-border/40 h-8">
                    <td className="p-2 truncate max-w-[260px]">{r.source_title ?? r.source_suggestion_id}</td>
                    <td className="p-2"><Badge variant="outline">{r.link_type}</Badge></td>
                    <td className="p-2 text-muted-foreground">{r.anchor_text}</td>
                    <td className="p-2 truncate max-w-[260px]">{r.target_title ?? r.target_suggestion_id}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </Card>
      </div>
    </div>
  );
}
